[package]
name = "shtts-web"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
description = "WebAssembly bindings for SHTTS"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
shtts = { path = "../.." }
wasm-bindgen = "=0.2.120"

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
    "-O3",
    "--enable-bulk-memory",
    "--enable-nontrapping-float-to-int",
    "--strip-debug",
    "--strip-producers",
]
